/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 cup2_low_re.glb -t -d
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Model: THREE.Mesh
  }
  materials: {
    ['material0.005']: THREE.MeshStandardMaterial
  }
}

export function Cup2(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./models/low_re/cup2_low_re.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Model.geometry} material={materials['material0.005']} material-metalness={0.14} material-roughness={1} rotation={[1.35, 0, -0.83]} />
    </group>
  )
}

// useGLTF.preload('./models/low_re/cup2_low_re.glb')
