/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 disk_low_re.glb -t -d -TRS
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Model: THREE.Mesh
  }
  materials: {
    ['material0.007']: THREE.MeshStandardMaterial
  }
}

export function DiskSimpled(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./models/low_re/transformed/disk_low_re-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Model.geometry} material={materials['material0.007']} material-metalness={0.95} material-roughness={0.74} rotation={[0, 0, -0.94]} />
    </group>
  )
}

useGLTF.preload('./models/low_re/transformed/disk_low_re-transformed.glb')
