/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 bird2_low_re.glb -t -d -TRS
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Model: THREE.Mesh
  }
  materials: {
    ['material0.001']: THREE.MeshStandardMaterial
  }
}

export function Bird2Simpled(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./models/low_re/transformed/bird2_low_re-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Model.geometry} material={materials['material0.001']} material-metalness={0.95} material-roughness={0.62} position={[0, 0.01, 0]} rotation={[0.96, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./models/low_re/transformed/bird2_low_re-transformed.glb')
